// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzurpbnnwecwfvndozyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6dXJwYm5ud2Vjd2Z2bmRvenlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjk4MjEsImV4cCI6MjA2MjcwNTgyMX0.GyyFRmfsk5ouEJQyccYOoTndqD077CJMvIMrT3_ec9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);